Fix hash conflict when bundling or minify
terser and esbuild are not happy with this Godot esque naming 😂
* deg2rad
* rad2deg

Error from parcel v2
------------------------------------------------------------------------
@parcel/optimizer-esbuild: Transform failed with 1 error:
dist/index.HASH_REF_356077ebec9ab677.js:407:6: error: "$d36c7e27649d2ef4$export$b43ac6bc3494bec" has already been declared
------------------------------------------------------------------------
@parcel/optimizer-terser: "$d36c7e27649d2ef4$export$b43ac6bc3494bec" is redeclared

    406 | ;
  > 407 | const $d36c7e27649d2ef4$export$b43ac6bc3494bec = (radian)=>radian * (180 / $d36c7e27649d2ef4$var$PI)
  >     |      ^ "$d36c7e27649d2ef4$export$b43ac6bc3494bec" is redeclared
    408 | ;
    409 | const $d36c7e27649d2ef4$export$bf41f33ed18406c8 = (fn, args = [], setter = (setArg, callArg, index)=>callArg ?? setArg

  💡 It's likely that Terser doesn't support this syntax yet.
-----------------------------------------------------------------------